### ISSUE TITLE
validate-config fails on the comment-diff action

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubverse-actions#32]
In https://github.com/cdcepi/FluSight-forecast-hub/pull/1270 the check failed because comment-diff borked: 

```
/home/runner/work/_actions/carpentries/actions/main/comment-diff/node_modules/@octokit/request/dist-node/index.js:66
        const error = new requestError.RequestError(message, status, {
                      ^

RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/carpentries/actions/main/comment-diff/node_modules/@octokit/request/dist-node/index.js:66:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/home/runner/work/_actions/carpentries/actions/main/comment-diff/index.js:79:14) {
  status: '403',
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 11 Dec 2024 21:39:26 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'github.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-github-permissions': 'issues=write; pull_requests=write',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-api-version-selected': '2022-11-28',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '4781:39400A:3567EFF:69F9B4D:675A068E',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4993',
    'x-ratelimit-reset': '1733956165',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '7',
    'x-xss-protection': '0'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/cdcepi/FluSight-forecast-hub/issues/1270/comments',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.2.4 Node.js/20.18.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":":white_check_mark: Hub correctly configured!\\n\\n2024-12-11 21:39:26 UTC\\n"}',
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] {
          keepAlive: true,
          scheduling: 'lifo',
          timeout: 5000,
          noDelay: true,
          path: null
        },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {
          'api.github.com:443:::::::::::::::::::::': [ [TLSSocket] ]
        },
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:443:::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:443:::::::::::::::::::::' ]
        },
        [Symbol(shapeMode)]: false,
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound register]
    }
  },
  documentation_url: 'https://docs.github.com/rest/issues/comments#create-an-issue-comment'
}

Node.js v20.18.0
```

This is a new one to me and I am not quite sure what is happening with that, but I believe I need to set pull request write permissions in the workflow.

**Comment by zkamvar** [comment]
this is how we did it in the carpentries: https://github.com/carpentries/sandpaper-docs/blob/6121b43fcd7df7a0123d9b41bcf8f515b92489cd/.github/workflows/pr-comment.yaml#L158-L159

**Comment by annakrystalli** [comment]
Could this be at all related to the ubuntu changes?

**Comment by zkamvar** [comment]
> Could this be at all related to the ubuntu changes?

I don't think so; the OS should not affect permissions.

**Comment by zkamvar** [comment]
Also this is a tale as old as time: the flusight hub has outdated workflows and they don't explicitly have a `permissions` key.
